"use strict";

(function () {

	if (document.getElementById("about") != null) {

		console.log("About Page");
		var fh1;
		fh1 = document.getElementById("fh1");
		fh1.innerHTML = "Hey, I am Tarun."

		var firstpara;
		firstpara = document.getElementById("fpara");
		firstpara.innerHTML = "I am a Web Developer and I love building Web Applications."

		var secondpara;
		secondpara = document.getElementById("secpara");
		secondpara.innerHTML = "I am efficient at employing industry-standard technologies and principles to create dynamic web sites, applications, and interfaces based on a set of specifications and constraints, with a clear focus on the end user. I also have the skill-set of basic server-side components of modern web applications including databases and scripts. Additionally, I also apply entrepreneurial principles to the design and development of web-based projects.<br /> All this text is Generated by Javascript ..!"

		var thisDate = new Date();
		var thisYear = thisDate.getFullYear();
		document.getElementById('footer').innerHTML = "&copy; " + thisYear;

	}
	else if (document.getElementById("projects") != null) {
		console.log("Projects Page");

		thisDate = new Date();
		thisYear = thisDate.getFullYear();
		document.getElementById('footer').innerHTML = "&copy; " + thisYear;
	}
	else if (document.getElementById("contact") != null) {
		console.log("Contact Page");

		var name = document.getElementById("name");
		var email = document.getElementById("email");
		var comment = document.getElementById("comment");
		var button = document.getElementById("button");
		
		button.addEventListener("click", function(event){
		event.preventDefault();
		console.log("Name:" + name.value);
		console.log("Email: " + email.value);
		console.log("Comment: " + comment.value);

		thisDate = new Date();
		thisYear = thisDate.getFullYear();
		document.getElementById('footer').innerHTML = "&copy; " + thisYear;
		});
	}
})();

(function flash() {
    var stage = new createjs.Stage("canvas");
        var shape = new createjs.Shape();
 		shape.graphics.beginFill("#484b4b").drawRect(0, 0, 300, 250);
        stage.addChild(shape);
        createjs.Tween.get(shape, {loop: true})
          .to({x: 400}, 1000, createjs.Ease.getPowInOut(4))
          .to({alpha: 0, y: 75}, 500, createjs.Ease.getPowInOut(2))
          .to({alpha: 0, y: 125}, 100)
          .to({alpha: 1, y: 100}, 500, createjs.Ease.getPowInOut(2))
          .to({x: 100}, 800, createjs.Ease.getPowInOut(2));
        createjs.Ticker.setFPS(60);
        createjs.Ticker.addEventListener("tick", stage);
  })();